# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI - Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Daily at midnight
  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Because of scheduled runs, by default run on default branch
      with:
        ref: main
        path: workspace/coral

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install node libraries
      working-directory: workspace
      run: |
        cd coral
        npm install
        npm run build
              
    - name: Run CORAL tests
      working-directory: workspace/coral
      run: |
        npm run test
        if [ -f out/.failed ]; then exit 1; fi
